compressionLevel: mixed
enableGlobalCache: false
enableTelemetry: false
pnpMode: strict
npmScopes: {
  calmdown: {
    npmPublishRegistry: https://registry.npmjs.org,
    npmRegistryServer: https://registry.npmjs.org,
    npmAlwaysAuth: true,
    npmAuthToken: "${NPM_TOKEN}",
  }
}
