enableGlobalCache: false
enableTelemetry: false
enableScripts: true
compressionLevel: mixed
nodeLinker: pnp
pnpMode: strict
approvedGitRepositories:
  - "**"
npmMinimalAgeGate: 1w
npmPreapprovedPackages:
  - "@calmdown/*"
npmScopes:
  calmdown:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN:-}"
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"
