approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

enableTelemetry: false

npmMinimalAgeGate: 0

npmScopes:
  calmdown:
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_TOKEN:-}"
    npmPublishRegistry: "https://registry.npmjs.org"
    npmRegistryServer: "https://registry.npmjs.org"

pnpMode: strict
